### PR TITLE
3.1.1 amd 架构 docker 支持

### PR DESCRIPTION
**Pull request by FinleyGe**

### CODE REVIEW

**Comment by travelliu** [comment]
2023-04-06 at 14 01
为啥注释？

2023-04-06 at 14 02

文件名没改

**Comment by FinleyGe** [comment]
Sry I forgot that. I have fixed up now.

**Comment by travelliu** [comment]
ok. we will add 3.1.1 arm64. and 5.0.0. Merge together

**Comment by FinleyGe** [comment]
thanks!

**Comment by su-houzhen** [comment]
@FinleyGe Is this image working fine in your test?

I got an error while testing.

image

**Comment by FinleyGe** [comment]
> @FinleyGe Is this image working fine in your test?
> 
> I got an error while testing.
> 
> image

Yeah, it's fine for me.
My Test Env is Archlinux 6.2.9-arch1-1 and Ubuntu 20.04 5.4.0-131-generic. (both of them are AMD)

Both of them are all okay.

This problem is weird.
It seems that the same problem causes when my friend tries to build the ARM version.

Maybe you need to post your env?
Or just try my image built up and posted to the docker repo.

```bash
docker pull finleyge/opengauss:3.1.1
```

**Comment by su-houzhen** [comment]
@FinleyGe  thks. It could also be a problem with WSL. I will try this later.

**Pull request merged**
